"""add_inventory_supplier

Revision ID: 8549ab6f8a8f
Revises: c2147b79d79a
Create Date: 2026-02-25 01:35:37.850648

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8549ab6f8a8f'
down_revision = 'c2147b79d79a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_inventory_supplier_id_suppliers',
            'suppliers',
            ['supplier_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_supplier_id_suppliers', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_supplier_id'))
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###
