"""add product barcode

Revision ID: 86a189e456de
Revises: a38ba6e0d1ba
Create Date: 2026-02-22 04:11:45.854743

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '86a189e456de'
down_revision = 'a38ba6e0d1ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_barcode'))
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###
