"""expand_schema

Revision ID: a38ba6e0d1ba
Revises: 74fdb9e66154
Create Date: 2026-02-22 03:42:48.369659

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a38ba6e0d1ba'
down_revision = '74fdb9e66154'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_code'), ['code'], unique=True)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('change_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=200), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('uom', sa.String(length=200), nullable=False),
    sa.Column('initial_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_depleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_units_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_stock_units_variant_id'), ['variant_id'], unique=False)

    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('stock_unit_id', sa.Integer(), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['stock_unit_id'], ['stock_units.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_from_location_id'), ['from_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_stock_unit_id'), ['stock_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_to_location_id'), ['to_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_variant_id'), ['variant_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('stock_unit_id', sa.Integer(), nullable=True),
    sa.Column('pricing_mode', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('sku_snapshot', sa.String(length=64), nullable=True),
    sa.Column('uom_snapshot', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['stock_unit_id'], ['stock_units.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_stock_unit_id'), ['stock_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_variant_id'), ['variant_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roll_price', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('uom', sa.String(length=64), nullable=True))
        # Existing rows need a default when adding a NOT NULL column.
        batch_op.add_column(sa.Column('track_stock_unit', sa.Boolean(), nullable=False, server_default=sa.text("0")))
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('track_stock_unit')
        batch_op.drop_column('uom')
        batch_op.drop_column('roll_price')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_items_variant_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_stock_unit_id'))
        batch_op.drop_index(batch_op.f('ix_order_items_order_id'))

    op.drop_table('order_items')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_variant_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_to_location_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_stock_unit_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_from_location_id'))

    op.drop_table('inventory')
    with op.batch_alter_table('stock_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_units_variant_id'))
        batch_op.drop_index(batch_op.f('ix_stock_units_barcode'))

    op.drop_table('stock_units')
    op.drop_table('orders')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_code'))

    op.drop_table('locations')
    # ### end Alembic commands ###
