"""add order discounts

Revision ID: a9508539535e
Revises: a3645d851117
Create Date: 2026-02-24 00:41:43.691895

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a9508539535e'
down_revision = 'a3645d851117'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_mode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('discount_total', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_mode', sa.String(length=10), server_default=sa.text("'amount'"), nullable=False))
        batch_op.add_column(sa.Column('discount_value', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('discount_value')
        batch_op.drop_column('discount_mode')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('discount_total')
        batch_op.drop_column('discount_value')
        batch_op.drop_column('discount_mode')

    # ### end Alembic commands ###
