"""add customers suppliers

Revision ID: b18509332082
Revises: a9508539535e
Create Date: 2026-02-24 01:29:35.988294

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b18509332082'
down_revision = 'a9508539535e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('tax_code', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('debt', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=True)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('tax_code', sa.String(length=64), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account', sa.String(length=64), nullable=True),
    sa.Column('bank_branch', sa.String(length=200), nullable=True),
    sa.Column('debt', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_suppliers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_phone'))
        batch_op.drop_index(batch_op.f('ix_suppliers_name'))
        batch_op.drop_index(batch_op.f('ix_suppliers_code'))

    op.drop_table('suppliers')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_code'))

    op.drop_table('customers')
    # ### end Alembic commands ###
