"""add order customer

Revision ID: c2147b79d79a
Revises: b18509332082
Create Date: 2026-02-24 01:38:25.242424

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c2147b79d79a'
down_revision = 'b18509332082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_foreign_key('fk_orders_customer_id_customers', 'customers', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_customer_id_customers', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
